"use client";

import { useState } from "react";

type IconName="close"|"edit"|"chevron"|"minus"|"plus"|"save"|"download"|"sign"|"mail"|"print"|"file"|"folder"|"trash"|"search"|"spark"|"mic"|"send"|"history"|"check"|"grip"|"info";
const paths:Record<IconName,React.ReactNode>={
 close:<path d="M5 5l14 14M19 5L5 19"/>,edit:<><path d="M4 20h4L19 9l-4-4L4 16z"/><path d="M13 7l4 4"/></>,chevron:<path d="M7 9l5 5 5-5"/>,minus:<path d="M5 12h14"/>,plus:<path d="M12 5v14M5 12h14"/>,save:<><path d="M5 3h12l2 2v16H5z"/><path d="M8 3v6h8V3M8 21v-7h8v7"/></>,download:<><path d="M12 3v12M8 11l4 4 4-4"/><path d="M5 20h14"/></>,sign:<><path d="M4 18c3-5 4-8 6-8 2 0-1 7 1 7 1 0 2-3 3-3s0 3 2 3c1 0 2-1 4-3"/><path d="M4 21h16"/></>,mail:<><rect x="3" y="5" width="18" height="14" rx="2"/><path d="M3 7l9 6 9-6"/></>,print:<><path d="M6 9V3h12v6M6 18h12v3H6z"/><rect x="3" y="9" width="18" height="9" rx="2"/></>,file:<><path d="M5 3h11l3 3v15H5Z"/><path d="M9 13h6M9 17h4"/></>,folder:<path d="M3 7a2 2 0 0 1 2-2h4l2 2.5h8a2 2 0 0 1 2 2V18a2 2 0 0 1-2 2H5a2 2 0 0 1-2-2Z"/>,trash:<><path d="M4 7h16M9 7V4h6v3M7 7l1 14h8l1-14"/></>,search:<><circle cx="11" cy="11" r="7"/><path d="M16 16l5 5"/></>,spark:<path d="M12 3l2.2 5.8L20 11l-5.8 2.2L12 19l-2.2-5.8L4 11l5.8-2.2Z"/>,mic:<><rect x="9" y="3" width="6" height="12" rx="3"/><path d="M5 11a7 7 0 0 0 14 0M12 18v3"/></>,send:<><path d="M3 11l18-8-8 18-2-8z"/><path d="M11 13l5-5"/></>,history:<><path d="M4 12a8 8 0 1 0 3-6"/><path d="M4 4v5h5M12 8v5l3 2"/></>,check:<path d="M5 12l5 5L20 7"/>,grip:<><circle cx="8" cy="6" r="1"/><circle cx="8" cy="12" r="1"/><circle cx="8" cy="18" r="1"/><circle cx="16" cy="6" r="1"/><circle cx="16" cy="12" r="1"/><circle cx="16" cy="18" r="1"/></>,info:<><circle cx="12" cy="12" r="9"/><path d="M12 11v6M12 7h.01"/></>
};
function Icon({name,size=18}:{name:IconName,size?:number}){return <svg className="fe-icon" width={size} height={size} viewBox="0 0 24 24" fill="none" stroke="currentColor" aria-hidden="true">{paths[name]}</svg>}

const library=["Additional Broker Acknowledgement – 6/23","Addendum #1 – 6/25","Buyer Inspection Advisory – 6/24","Market Conditions Advisory – 6/22"];

function PdfPage(){return <div className="fe-page"><div className="fe-seal"><div className="fe-car">CAR</div><div>CALIFORNIA<br/>ASSOCIATION<br/>OF REALTORS®</div><h1>DISCLOSURE REGARDING<br/>REAL ESTATE AGENCY RELATIONSHIP<small>(As required by the Civil Code)<br/>(C.A.R. Form AD, Revised 12/24)</small></h1></div><p><i/> (If checked) This form is being provided in connection with a transaction for a leasehold interest exceeding one year as per Civil Code §§ 2079.13(j), (k), and (l).</p><p>When you enter into a discussion with a real estate agent regarding a real estate transaction, you should from the outset understand what type of agency relationship or representation you wish to have with the agent in the transaction.</p><h2>SELLER&apos;S AGENT</h2><p>A Seller&apos;s agent under a listing agreement with the Seller acts as the agent for the Seller only. A Seller&apos;s agent or a subagent of that agent has the following affirmative obligations:<br/>To the Seller: A fiduciary duty of utmost care, integrity, honesty and loyalty in dealings with the Seller.<br/>To the Buyer and the Seller:</p><ol><li>Diligent exercise of reasonable skill and care in performance of the agent&apos;s duties.</li><li>A duty of honest and fair dealing and good faith.</li><li>A duty to disclose all facts known to the agent materially affecting the value or desirability of the property.</li></ol><h2>BUYER&apos;S AGENT</h2><p>A Buyer&apos;s agent can, with a Buyer&apos;s consent, agree to act as agent for the Buyer only. This includes a Buyer&apos;s agent under a buyer-broker representation agreement with the Buyer. In these situations, the agent is not the Seller&apos;s agent.</p><ol><li>A fiduciary duty of utmost care, integrity, honesty and loyalty in dealings with the Buyer.</li><li>Diligent exercise of reasonable skill and care in performance of the agent&apos;s duties.</li><li>A duty of honest and fair dealing and good faith.</li></ol><h2>AGENT REPRESENTING BOTH SELLER AND BUYER</h2><p>A real estate agent, either acting directly or through one or more salespersons and broker associates, can legally be the agent of both the Seller and the Buyer in a transaction, but only with the knowledge and consent of both.</p></div>}

function FormsPanel(){const [docs,setDocs]=useState(["California Residential Purchase Agreement – 6/26"]);return <div className="fe-panel-body"><section className="fe-panel-section"><div className="fe-section-title"><div><h3>Workspace</h3><button>What&apos;s this?</button></div><button className="fe-add"><Icon name="plus"/>Add</button></div><div className="fe-doc-actions"><button aria-label="Edit"><Icon name="edit"/></button><button aria-label="Email"><Icon name="mail"/></button><button aria-label="Download"><Icon name="download"/></button><button aria-label="Print"><Icon name="print"/></button><button aria-label="Delete"><Icon name="trash"/></button></div>{docs.map((doc,i)=><div className="fe-work-doc" key={doc}><Icon name="grip"/><span className="fe-checkbox"/><Icon name="file"/><div><b>{doc}</b><small>Form</small></div><button onClick={()=>setDocs(d=>d.filter((_,x)=>x!==i))} aria-label="Remove"><Icon name="close"/></button></div>)}<button className="fe-dropzone">Drag files from your transaction here</button></section><section className="fe-panel-section fe-library"><h3>Grab From Transaction</h3><div className="fe-search"><Icon name="search"/><input aria-label="Search forms" placeholder="Search for forms, documents..."/><button>All folders <Icon name="chevron" size={13}/></button></div>{library.map(item=><div className="fe-library-row" key={item}><Icon name="grip"/><span className="fe-checkbox"/><div><b>{item}</b><small>Form</small></div><button onClick={()=>setDocs(d=>d.includes(item)?d:[...d,item])} aria-label={`Add ${item}`}><Icon name="plus"/></button></div>)}</section></div>}

function AiPanel(){const [text,setText]=useState("");const [messages,setMessages]=useState<string[]>([]);return <div className="fe-ai"><div className="fe-ai-intro"><span><Icon name="spark"/></span><div><h3>Form Assistant</h3><p>Working with AD — Agency Relationship</p></div></div><div className="fe-thread"><div className="fe-ai-message">I can help you understand this clause, find missing fields, or fill the form using details from this transaction.</div><button><Icon name="spark"/>Explain the highlighted clause</button><button><Icon name="check"/>Check this form for missing fields</button>{messages.map((m,i)=><div className="fe-user-message" key={i}>{m}</div>)}</div><div className="fe-compose"><input value={text} onChange={e=>setText(e.target.value)} onKeyDown={e=>{if(e.key==="Enter"&&text.trim()){setMessages(v=>[...v,text]);setText("")}}} placeholder="Ask about this form..."/><button aria-label="Send" onClick={()=>{if(text.trim()){setMessages(v=>[...v,text]);setText("")}}}><Icon name="send"/></button></div></div>}

function VoicePanel(){const [recording,setRecording]=useState(false);return <div className="fe-voice"><div className={recording?"fe-orb recording":"fe-orb"}><Icon name="mic" size={28}/></div><h3>{recording?"Listening…":"Fill forms by voice"}</h3><p>{recording?"Describe the parties, property, dates, and terms naturally.":"Speak naturally. Orqestron maps your words to the correct fields while the document stays in view."}</p><button className="fe-record" onClick={()=>setRecording(!recording)}>{recording?"Stop & review":"Start voice fill"}</button><div className="fe-transcript"><span>LIVE TRANSCRIPT</span><p>{recording?"Buyer Ariya Anna is purchasing the property at 2458 Maplewood Avenue, unit 12B…":"Your transcript and detected fields will appear here."}</p></div><div className="fe-detected"><div><span>Buyer name</span><b>Ariya Anna</b><Icon name="check"/></div><div><span>Property</span><b>2458 Maplewood Ave 12B</b><Icon name="check"/></div></div></div>}

export default function Page(){const [panel,setPanel]=useState<"forms"|"ai"|"voice">("forms");const [zoom,setZoom]=useState("Fit width");return <main className="form-editor"><header className="fe-heading"><button className="fe-close"><Icon name="close"/>Close</button><div className="fe-title">[BRBC] Buyer Representation and Broker Compensation Agreement <button aria-label="Edit title"><Icon name="edit" size={15}/></button></div><b>2458 Maplewood Ave 12B, Los Angeles, CA 90026</b></header><div className="fe-toolbar"><div className="fe-zoom"><button onClick={()=>setZoom(zoom==="Fit width"?"100%":"Fit width")}>{zoom}<Icon name="chevron" size={13}/></button><span>1</span><i>/</i><span>13</span></div><div className="fe-tool-actions"><button><Icon name="save"/><span>Save</span></button><button><Icon name="download"/><span>Download</span></button><button><Icon name="sign"/><span>Sign</span></button><button><Icon name="mail"/><span>Email</span></button></div></div><div className="fe-content"><section className="fe-canvas"><div className="fe-doc-caption"><span>Disclosure Regarding Real Estate Agency Relationship</span><b>1 / 25</b></div><PdfPage/><button className="fe-info" aria-label="Document information"><Icon name="info"/></button></section><aside className="fe-context"><header><div><h2>{panel==="forms"?"Forms and Documents":panel==="ai"?"AI Assistant":"Voice Fill"}</h2><p>{panel==="forms"?"Manage this transaction’s document set":panel==="ai"?"Ask, review, and fill in context":"Speak details directly into form fields"}</p></div><button aria-label="Close panel"><Icon name="close"/></button></header>{panel==="forms"?<FormsPanel/>:panel==="ai"?<AiPanel/>:<VoicePanel/>}</aside><nav className="fe-mode-rail" aria-label="Workspace modes"><button className={panel==="forms"?"active":""} onClick={()=>setPanel("forms")}><Icon name="file"/><span>Forms</span></button><button className={panel==="ai"?"active":""} onClick={()=>setPanel("ai")}><Icon name="spark"/><span>AI</span></button><button className={panel==="voice"?"active":""} onClick={()=>setPanel("voice")}><Icon name="mic"/><span>Voice</span></button></nav></div></main>}
