"use client";

import { useState } from "react";

type IconName = "folder"|"file"|"user"|"users"|"home"|"sun"|"library"|"bell"|"panel"|"edit"|"send"|"more"|"chevron"|"download"|"chat"|"fields"|"fullscreen"|"spark"|"plus"|"history"|"check"|"mic"|"arrow"|"eye";
const iconPaths: Record<IconName, React.ReactNode> = {
  folder:<path d="M3 7a2 2 0 0 1 2-2h4l2 2.5h8a2 2 0 0 1 2 2V18a2 2 0 0 1-2 2H5a2 2 0 0 1-2-2Z"/>, file:<><path d="M5 3h11l3 3v15H5Z"/><path d="M9 13h6M9 17h4"/></>,
  user:<><circle cx="12" cy="8" r="3.2"/><path d="M5.5 20a6.5 6.5 0 0 1 13 0"/></>, users:<><circle cx="9" cy="8" r="3"/><path d="M3 20c0-3.5 2.5-6 6-6s6 2.5 6 6M16 5.5a3 3 0 0 1 0 5.8M17 14c2.4.5 4 2.6 4 5"/></>,
  home:<><path d="M3 11l9-7 9 7"/><path d="M5 10v10h14V10"/></>, sun:<><circle cx="12" cy="12" r="3"/><path d="M12 2v4M12 18v4M2 12h4M18 12h4M4.9 4.9l2.8 2.8M16.3 16.3l2.8 2.8M19.1 4.9l-2.8 2.8M7.7 16.3l-2.8 2.8"/></>,
  library:<><path d="M4 4h4v16H4zM10 4h4v16h-4zM16 4h4v16h-4z"/><path d="M5 8h2M11 8h2M17 8h2"/></>, bell:<><path d="M18 9a6 6 0 0 0-12 0c0 7-3 7-3 9h18c0-2-3-2-3-9"/><path d="M10 21h4"/></>,
  panel:<><rect x="3" y="4" width="18" height="16" rx="2"/><path d="M9 4v16"/></>, edit:<><path d="M4 20h4L19 9l-4-4L4 16z"/><path d="M13 7l4 4"/></>, send:<><path d="M3 11l18-8-8 18-2-8z"/><path d="M11 13l5-5"/></>,
  more:<><circle cx="5" cy="12" r="1.3"/><circle cx="12" cy="12" r="1.3"/><circle cx="19" cy="12" r="1.3"/></>, chevron:<path d="M6 9l6 6 6-6"/>, download:<><path d="M12 3v12M8 11l4 4 4-4"/><path d="M5 19h14"/></>, chat:<path d="M21 15a2 2 0 0 1-2 2H7l-4 4V5a2 2 0 0 1 2-2h14a2 2 0 0 1 2 2z"/>,
  fields:<><path d="M4 7h16M4 12h10M4 17h7"/><circle cx="19" cy="17" r="2"/></>, fullscreen:<path d="M15 3h6v6M9 21H3v-6M21 3l-7 7M3 21l7-7"/>, spark:<path d="M12 3l2.2 5.8L20 11l-5.8 2.2L12 19l-2.2-5.8L4 11l5.8-2.2Z"/>,
  plus:<path d="M12 5v14M5 12h14"/>, history:<><path d="M4 12a8 8 0 1 0 3-6"/><path d="M4 4v5h5M12 8v5l3 2"/></>, check:<><path d="M9 11l3 3L22 4"/><path d="M21 12v7a2 2 0 0 1-2 2H5a2 2 0 0 1-2-2V5a2 2 0 0 1 2-2h11"/></>,
  mic:<><rect x="9" y="3" width="6" height="12" rx="3"/><path d="M5 11a7 7 0 0 0 14 0M12 18v3"/></>, arrow:<path d="M5 12h14M13 5l7 7-7 7"/>, eye:<><path d="M2 12s4-6 10-6 10 6 10 6-4 6-10 6S2 12 2 12"/><circle cx="12" cy="12" r="2.5"/></>,
};
const Icon = ({ name, size=18 }: { name: IconName; size?: number }) => <svg className="line-icon" width={size} height={size} viewBox="0 0 24 24" fill="none" stroke="currentColor" aria-hidden="true">{iconPaths[name]}</svg>;
const folders = [{ name: "Compliance", count: 6 },{ name: "Buyer Representation", count: 2 },{ name: "Purchase Agreement", count: 4 }];
const assistantItems = [["BRBC", "Buyer Representation", "32/133 filled"],["AD", "Agency Disclosure", "7/15 filled"],["PRBS", "Possible Representation", "7/11 filled (currently open)"],["SBSA", "Statewide Advisory", "3/31 filled"],["RAD", "REALTOR® Acknowledgement", "8/51 filled"],["ABAD", "Affiliated Business Disclosure", "1/10 filled"],["FHDA", "Fair Housing Advisory", "1/19 filled"]];

function Rail() { return <aside className="rail"><button className="logo" aria-label="Orqestron home">O</button><nav><button aria-label="Projects"><Icon name="folder"/></button><button aria-label="Forms"><Icon name="file"/></button><button aria-label="Contacts"><Icon name="users"/></button><button aria-label="Quick forms"><Icon name="file"/></button><span/><button aria-label="Theme"><Icon name="sun"/></button><button aria-label="Library"><Icon name="library"/></button></nav><button className="rail-bell" aria-label="Notifications"><Icon name="bell" size={16}/></button></aside> }

function DealHeader() {
  const [phase, setPhase] = useState(0); const phases = ["Onboarding", "Touring", "Offer", "Escrow", "Closing"];
  return <><header className="deal-head"><button className="sidebar-toggle" aria-label="Toggle sidebar"><Icon name="panel"/></button><div><div className="deal-title">Ariya Anna <button aria-label="Edit deal name"><Icon name="edit" size={13}/></button></div><small>CA · New Leads</small></div><div className="crumbs">Pipeline <i>/</i> Projects <i>/</i> <b>Ariya Anna</b> <span>BUYER</span></div></header><div className="phase-row"><div className="phases" aria-label="Deal phase">{phases.map((name,index)=><button key={name} onClick={()=>setPhase(index)} className={phase===index?"active":phase>index?"done":""}>{name}</button>)}</div><button className="advance" onClick={()=>setPhase((phase+1)%phases.length)}>Advance phase</button><button className="more" aria-label="More options"><Icon name="more"/></button></div><div className="tabs"><button className="active">Dashboard</button><button>Key Dates</button><button>Tasks</button><button className="send-sign"><Icon name="send" size={13}/>Send for Signature</button></div></>;
}

function FileTree() {
  const [open,setOpen]=useState<Record<string,boolean>>({"Purchase Agreement":true});
  return <aside className="file-panel"><section className="property-card"><label>PROPERTY</label><button><Icon name="home" size={15}/><b>CA</b><span><Icon name="chevron" size={14}/></span></button></section><section className="files-card"><div className="section-label">FILES <button aria-label="Hide file tree"><Icon name="panel" size={15}/></button></div><label className="mini-label">PROFILES</label><button className="profile-row"><Icon name="user"/><b>Client Profile</b></button><button className="profile-row"><Icon name="home"/><b>Property Profile</b></button><button className="profile-row"><Icon name="users"/><b>Buyer&apos;s Agents</b></button><div className="mini-label client-label">CLIENT DOCUMENTS <span>· all phases</span></div>{folders.map(folder=><div key={folder.name}><button className="folder-row" onClick={()=>setOpen(v=>({...v,[folder.name]:!v[folder.name]}))}><span className={open[folder.name]?"tree-chevron open":"tree-chevron"}><Icon name="chevron" size={13}/></span><Icon name="folder" size={17}/><b>{folder.name}</b><small><em>{folder.count} ITEMS</em> · {folder.count} forms</small></button>{open[folder.name]&&<div className="form-list"><div className="form-heading">CORE FORMS <span>4</span></div><button className="form-row active"><Icon name="file" size={14}/>AD — Disclosure Regarding Real Estate Agency Relationship.pdf</button><button className="form-row"><Icon name="file" size={14}/>RPA — California Residential Purchase Agreement.pdf</button></div>}</div>)}</section></aside>;
}

function Paper() { return <div className="paper-wrap"><div className="paper"><div className="paper-brand"><span className="car-mark">◢</span><small>CALIFORNIA<br/>ASSOCIATION<br/>OF REALTORS®</small><h2>DISCLOSURE REGARDING<br/>REAL ESTATE AGENCY RELATIONSHIP</h2></div><p className="paper-sub">(As required by the Civil Code)<br/>(C.A.R. Form AD, Revised 12/24)</p><p><i className="box"/> (If checked) This form is being provided in connection with a transaction for a leasehold interest exceeding one year per Civil Code §§ 2079.13(j), (k), and (l).</p><p>When you enter into a discussion with a real estate agent regarding a real estate transaction, you should from the outset understand what type of agency relationship or representation you wish to have with the agent in the transaction.</p><h3>SELLER&apos;S AGENT</h3><p>A Seller&apos;s agent under a listing agreement with the Seller acts as the agent for the Seller. A Seller&apos;s agent or a subagent of that agent has the following affirmative obligations:</p><ol><li>A fiduciary duty of utmost care, integrity, honesty and loyalty in dealings with the Seller.</li><li>A duty of honest and fair dealing and good faith.</li><li>A duty to disclose all facts known to the agent materially affecting the value or desirability of the property.</li></ol><h3>BUYER&apos;S AGENT</h3><p>A Buyer&apos;s agent can, with a Buyer&apos;s consent, agree to act as agent for the Buyer only. This includes a Buyer&apos;s agent under a buyer-broker representation agreement with the Buyer.</p><h3>AGENT REPRESENTING BOTH SELLER AND BUYER</h3>{Array.from({length:22}).map((_,i)=><div className="legal-line" key={i}>{i%4===0?"A real estate agent may represent both the Seller and the Buyer in a transaction with the knowledge and consent of both parties.":"The duties of a real estate agent in a transaction are governed by law and the terms of the agency relationship."}</div>)}</div></div> }

function Editor() { const [zoom,setZoom]=useState(100); return <main className="editor-panel"><div className="editor-top"><div className="mode"><button className="active"><Icon name="edit" size={13}/>Edit</button><button><Icon name="eye" size={13}/>Preview</button></div><div><button><Icon name="download" size={13}/>Export PDF <Icon name="chevron" size={11}/></button><button><Icon name="chat" size={13}/>Hide AI Chat</button></div></div><div className="editor-sub"><button><Icon name="fields" size={13}/>Next field <span>(1/560)</span></button><div>Page <input value="1" readOnly/> / 25 <button>Go</button></div></div><Paper/><div className="zoom"><button onClick={()=>setZoom(Math.max(50,zoom-10))}>−</button><b>{zoom}%</b><button onClick={()=>setZoom(Math.min(150,zoom+10))}>＋</button><i/><button aria-label="View fullscreen"><Icon name="fullscreen" size={15}/></button></div></main> }

function Assistant() {
  const [message,setMessage]=useState(""); const [sent,setSent]=useState<string[]>([]); const submit=()=>{if(message.trim()){setSent(v=>[...v,message]);setMessage("")}};
  return <aside className="assistant-panel"><header><span className="spark"><Icon name="spark" size={20}/></span><div><b>Initial real estate inquiry</b><small>RPA — California Residential Pu...</small></div><button aria-label="Open guided form"><Icon name="file" size={15}/></button><button aria-label="New chat"><Icon name="plus" size={16}/></button><button aria-label="Chat history"><Icon name="history" size={16}/></button></header><div className="conversation"><p>Hello! I&apos;m the form agent assistant, created by Orqestron. I&apos;m here to help you get your forms ready for Ariya Anna&apos;s deal.</p><p>We&apos;re currently in the <b>Onboarding</b> phase. Here is where we stand with the active forms:</p><ul>{assistantItems.map(item=><li key={item[0]}><b>{item[0]}</b> ({item[1]}) — {item[2]}</li>)}</ul><p>The <b>PRBS</b> is already open and just needs a few more details to finish. Would you like to start there, or should we jump into the <b>BRBC</b>?</p>{sent.map((text,i)=><p className="user-message" key={i}>{text}</p>)}</div><div className="context-card"><Icon name="file" size={15}/><div><b>RPA — California R...</b><small>Current form context</small></div><button><Icon name="spark" size={13}/>Continue filling</button><i>×</i></div><div className="quick-actions"><button><Icon name="spark" size={13}/></button><button className="active"><Icon name="arrow" size={13}/>Continue</button><button><Icon name="chevron" size={13}/>Next form</button><button><Icon name="check" size={13}/>Check status</button></div><div className="prompt"><input value={message} onChange={e=>setMessage(e.target.value)} onKeyDown={e=>e.key==="Enter"&&submit()} placeholder="Ask about a clause or field..."/><button aria-label="Voice input"><Icon name="mic" size={15}/></button><button className="submit" onClick={submit} aria-label="Send message"><Icon name="send" size={15}/></button></div></aside>;
}

export default function Page(){return <div className="workspace-app"><Rail/><section className="workspace"><DealHeader/><div className="workspace-grid"><FileTree/><Editor/><Assistant/></div></section></div>}
