"use client";

import { useState } from "react";

const Icon = ({ children }: { children: React.ReactNode }) => <span className="line-icon" aria-hidden="true">{children}</span>;
const folders = [{ name: "Compliance", count: 6 },{ name: "Buyer Representation", count: 2 },{ name: "Purchase Agreement", count: 4 }];
const assistantItems = [["BRBC", "Buyer Representation", "32/133 filled"],["AD", "Agency Disclosure", "7/15 filled"],["PRBS", "Possible Representation", "7/11 filled (currently open)"],["SBSA", "Statewide Advisory", "3/31 filled"],["RAD", "REALTOR® Acknowledgement", "8/51 filled"],["ABAD", "Affiliated Business Disclosure", "1/10 filled"],["FHDA", "Fair Housing Advisory", "1/19 filled"]];

function Rail() { return <aside className="rail"><button className="logo" aria-label="Orqestron home">O</button><nav><button aria-label="Projects"><Icon>▱</Icon></button><button aria-label="Forms"><Icon>▤</Icon></button><button aria-label="Contacts"><Icon>♧</Icon></button><button aria-label="Quick forms"><Icon>♧</Icon></button><span/><button aria-label="Theme"><Icon>☼</Icon></button><button aria-label="Library"><Icon>▥</Icon></button></nav><button className="rail-bell" aria-label="Notifications">♢</button></aside> }

function DealHeader() {
  const [phase, setPhase] = useState(0); const phases = ["Onboarding", "Touring", "Offer", "Escrow", "Closing"];
  return <><header className="deal-head"><button className="sidebar-toggle" aria-label="Toggle sidebar">◧</button><div><div className="deal-title">Ariya Anna <button aria-label="Edit deal name">⌁</button></div><small>CA · New Leads</small></div><div className="crumbs">Pipeline <i>/</i> Projects <i>/</i> <b>Ariya Anna</b> <span>BUYER</span></div></header><div className="phase-row"><div className="phases" aria-label="Deal phase">{phases.map((name,index)=><button key={name} onClick={()=>setPhase(index)} className={phase===index?"active":phase>index?"done":""}>{name}</button>)}</div><button className="advance" onClick={()=>setPhase((phase+1)%phases.length)}>Advance phase</button><button className="more" aria-label="More options">•••</button></div><div className="tabs"><button className="active">Dashboard</button><button>Key Dates</button><button>Tasks</button><button className="send-sign">⌁&nbsp; Send for Signature</button></div></>;
}

function FileTree() {
  const [open,setOpen]=useState<Record<string,boolean>>({"Purchase Agreement":true});
  return <aside className="file-panel"><section className="property-card"><label>PROPERTY</label><button>⌂ <b>CA</b><span>⌄</span></button></section><section className="files-card"><div className="section-label">FILES <button aria-label="Hide file tree">◫</button></div><label className="mini-label">PROFILES</label><button className="profile-row"><Icon>♙</Icon><b>Client Profile</b></button><button className="profile-row"><Icon>⌂</Icon><b>Property Profile</b></button><button className="profile-row"><Icon>♧</Icon><b>Buyer&apos;s Agents</b></button><div className="mini-label client-label">CLIENT DOCUMENTS <span>· all phases</span></div>{folders.map(folder=><div key={folder.name}><button className="folder-row" onClick={()=>setOpen(v=>({...v,[folder.name]:!v[folder.name]}))}><span>{open[folder.name]?"⌄":"›"}</span><Icon>□</Icon><b>{folder.name}</b><small><em>{folder.count} ITEMS</em> · {folder.count} forms</small></button>{open[folder.name]&&<div className="form-list"><div className="form-heading">CORE FORMS <span>4</span></div><button className="form-row active">AD — Disclosure Regarding Real Estate Agency Relationship.pdf</button><button className="form-row">RPA — California Residential Purchase Agreement.pdf</button></div>}</div>)}</section></aside>;
}

function Paper() { return <div className="paper-wrap"><div className="paper"><div className="paper-brand"><span className="car-mark">◢</span><small>CALIFORNIA<br/>ASSOCIATION<br/>OF REALTORS®</small><h2>DISCLOSURE REGARDING<br/>REAL ESTATE AGENCY RELATIONSHIP</h2></div><p className="paper-sub">(As required by the Civil Code)<br/>(C.A.R. Form AD, Revised 12/24)</p><p><i className="box"/> (If checked) This form is being provided in connection with a transaction for a leasehold interest exceeding one year per Civil Code §§ 2079.13(j), (k), and (l).</p><p>When you enter into a discussion with a real estate agent regarding a real estate transaction, you should from the outset understand what type of agency relationship or representation you wish to have with the agent in the transaction.</p><h3>SELLER&apos;S AGENT</h3><p>A Seller&apos;s agent under a listing agreement with the Seller acts as the agent for the Seller. A Seller&apos;s agent or a subagent of that agent has the following affirmative obligations:</p><ol><li>A fiduciary duty of utmost care, integrity, honesty and loyalty in dealings with the Seller.</li><li>A duty of honest and fair dealing and good faith.</li><li>A duty to disclose all facts known to the agent materially affecting the value or desirability of the property.</li></ol><h3>BUYER&apos;S AGENT</h3><p>A Buyer&apos;s agent can, with a Buyer&apos;s consent, agree to act as agent for the Buyer only. This includes a Buyer&apos;s agent under a buyer-broker representation agreement with the Buyer.</p><h3>AGENT REPRESENTING BOTH SELLER AND BUYER</h3>{Array.from({length:22}).map((_,i)=><div className="legal-line" key={i}>{i%4===0?"A real estate agent may represent both the Seller and the Buyer in a transaction with the knowledge and consent of both parties.":"The duties of a real estate agent in a transaction are governed by law and the terms of the agency relationship."}</div>)}</div></div> }

function Editor() { const [zoom,setZoom]=useState(100); return <main className="editor-panel"><div className="editor-top"><div className="mode"><button className="active">⌕ Edit</button><button>◉ Preview</button></div><div><button>⇩&nbsp; Export PDF⌄</button><button>◩&nbsp; Hide AI Chat</button></div></div><div className="editor-sub"><button>☷ Next field <span>(1/560)</span></button><div>Page <input value="1" readOnly/> / 25 <button>Go</button></div></div><Paper/><div className="zoom"><button onClick={()=>setZoom(Math.max(50,zoom-10))}>−</button><b>{zoom}%</b><button onClick={()=>setZoom(Math.min(150,zoom+10))}>＋</button><i/><button>↗</button></div></main> }

function Assistant() {
  const [message,setMessage]=useState(""); const [sent,setSent]=useState<string[]>([]); const submit=()=>{if(message.trim()){setSent(v=>[...v,message]);setMessage("")}};
  return <aside className="assistant-panel"><header><span className="spark">✣</span><div><b>Initial real estate inquiry</b><small>RPA — California Residential Pu...</small></div><button>▧</button><button>＋</button><button>↶</button></header><div className="conversation"><p>Hello! I&apos;m the form agent assistant, created by Orqestron. I&apos;m here to help you get your forms ready for Ariya Anna&apos;s deal.</p><p>We&apos;re currently in the <b>Onboarding</b> phase. Here is where we stand with the active forms:</p><ul>{assistantItems.map(item=><li key={item[0]}><b>{item[0]}</b> ({item[1]}) — {item[2]}</li>)}</ul><p>The <b>PRBS</b> is already open and just needs a few more details to finish. Would you like to start there, or should we jump into the <b>BRBC</b>?</p>{sent.map((text,i)=><p className="user-message" key={i}>{text}</p>)}</div><div className="context-card"><span>▧</span><div><b>RPA — California R...</b><small>Current form context</small></div><button>✣ Continue filling</button><i>×</i></div><div className="quick-actions"><button>ϟ</button><button className="active">› Continue</button><button>› Next form</button><button>☑ Check status</button></div><div className="prompt"><input value={message} onChange={e=>setMessage(e.target.value)} onKeyDown={e=>e.key==="Enter"&&submit()} placeholder="Ask about a clause or field..."/><button>♩</button><button className="submit" onClick={submit}>⌁</button></div></aside>;
}

export default function Page(){return <div className="workspace-app"><Rail/><section className="workspace"><DealHeader/><div className="workspace-grid"><FileTree/><Editor/><Assistant/></div></section></div>}
